# -*- coding: utf-8 -*-
"""text to image.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KhevDXDFQksc2MbD7YnFqdamGQCH2jlG
"""

!pip install transformers torch diffusers accelerate pillow opencv-python ultralytics

import torch
from transformers import GPT2LMHeadModel, GPT2Tokenizer
from diffusers import StableDiffusionPipeline
from PIL import Image
import cv2
from ultralytics import YOLO

device = "cuda" if torch.cuda.is_available() else "cpu"

# --- 1. TEXT GENERATION
def generate_text(prompt="A CAT"):
    tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
    model = GPT2LMHeadModel.from_pretrained("gpt2").to(device)
    inputs = tokenizer(prompt, return_tensors="pt").to(device)
    outputs = model.generate(
        **inputs,
        max_length=20,
        num_return_sequences=1,
        pad_token_id=tokenizer.eos_token_id
    )

    generated_text = tokenizer.decode(outputs[0], skip_special_tokens=True)
    print(f"Generated Text: {generated_text}")
    return generated_text

# --- 2. IMAGE GENERATION
def generate_image(prompt):
    pipe = StableDiffusionPipeline.from_pretrained(
        "runwayml/stable-diffusion-v1-5",
        torch_dtype=torch.float16 if device == "cuda" else torch.float32
    ).to(device)

    image = pipe(prompt).images[0]
    image_path = "generated_image.png"
    image.save(image_path)
    print(f"Image saved to {image_path}")
    return image_path

# --- 3. OBJECT DETECTION
def detect_objects(image_path):
    model = YOLO("yolov8n.pt")

    results = model(image_path)
    results[0].show()

    detections = results[0].boxes.data.tolist()
    class_names = results[0].names
    print("Detected Objects:")
    for det in detections:
        x1, y1, x2, y2, conf, cls_id = det
        print(f"- {class_names[int(cls_id)]} (Confidence: {conf:.2f})")


if __name__ == "__main__":
    input_prompt = input("Enter a text prompt (e.g., 'A CAT'): ").strip()
    generated_text = generate_text(input_prompt)
    image_path = generate_image(generated_text)
    detect_objects(image_path)